In [1]:
import csv
import os
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

/var/folders/59/mg36zpzn3fqbx4_xccrmb89m0000gn/T/ipykernel_46973/4292752259.py:5: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import TextLoader

In [ ]:
from dotenv import load_dotenv
load_dotenv()

True

In [ ]:
import pandas as pd
import numpy as np

In [4]:
books = pd.read_csv("data/books_cleaned.csv")

In [5]:
books.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."

In [6]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: str

In [7]:
books["tagged_description"].to_csv(
    "data/tagged_description.txt",
    index=False,
    header=False,
    quoting=csv.QUOTE_NONE,
    escapechar="\\",
)

In [8]:
raw_documents = TextLoader("data/tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=10000, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

In [9]:
documents[0]

Document(metadata={'source': 'data/tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade\\, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher\\, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead\\, Iowa\\, towards the end of the Reverend Ames’s life\\, and he is absorbed in recording his family’s story\\, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence\\, John tells of the rift between his grandfather and his father: the elder\\, an angry visionary who fought for the abolitionist cause\\, and his son\\, an ardent pacifist. He is troubled\\, too\\, by his prodigal namesake\\, Jack (John Ames) Boughton\\, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous\\, rambling voice that finds beauty\\, humour and truth in the smallest of life’s details\\, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons\\, pitch-perfect in style and story\\, set to dazzle critics and readers alike.\n9780002261982 A new \'Christie for Christmas\' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation\\, bringing her superb storytelling to a new legion of fans. Clarissa\\, the wife of a Foreign Office diplomat\\, is given to daydreaming. \'Supposing I were to come down one morning and find a dead body in the library\\, what should I do?\' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician\\, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?)\\, and the search begins for the murderer and the motive\\, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER\'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI\n9780006178736 A memorable\\, mesmerizing heroine Jennifer -- brilliant\\, beautiful\\, an attorney on the way up until the Mafia\'s schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous\\, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power.\n9780006280897 Lewis\' work on the nature of love divides love into four categories; Affection\\, Friendship\\, Eros and Charity. The first three come naturally to humanity. Charity\\, however\\, the Gift-love of God\\, is divine\\, and without this supernatural love\\, the natural loves become distorted and even dangerous.\n9780006280934 \\"In The Problem of Pain\\, C.S. Lewis\\, one of the most renowned Christian authors and thinkers\\, examines a universally applicable question within the human condition: If God is good and all-powerful\\, why does he allow his creatures to suffer pain? With his signature wealth of compassion and insight\\, C.S. Lewis offers answers to these crucial questions and shares his hope and wisdom to help heal a world hungering for a true understanding of human nature.\\"--Amazon.\n9780006380832 Until Vasco da Gama discovered the sea-route to the East in 1497-9 almost nothing was known in the West of the exotic cultures and wealth of the Indian Ocean and its peoples. It is this civilization and its destruction at the hands of the West that Richard Hall recreates in this book. Hall\'s history of the exploration and exploitation by Chinese and Arab travellers\\, and by the Portuguese\\, Dutch and British alike is one of brutality\\, betrayal and colonial ambition.\n9780006470229 A new-cover reissue of the fourth book in the bestselling five-volume sf series created by the world-famous author of the Thomas Covenant chronicles -- and acclaimed as the \'best work of his career\'. Events were not moving as the Amnion had intended. Once again humans had been false in their dealings with the aliens. As the planetoid Thanatos Minor exploded into atoms\\, the Trumpet hurtled into space only one step ahead of hostile pursuers. On board were Morn Hyland and her force-grown son Davies\\, cyborg Angus Thermopyle and Captain Nick Succorso -- old enemies thrown together in a desperate bid for survival. For both the Amnion and the UMCP\\, the immediate capture of the fleeing ship and the secrets it contained was imperative. But for Trumpet\'s exhausted crew the only hope lay in an illegal lab in the distant binary solar system of Valdor Industrial. It would be a journey of unpredictable danger -- from which not all would return...\n9780006472612 Kate Blackwell is an enigma and one of the most powerful women in the world. But at her ninetieth birthday celebrations there are ghosts of absent friends and absent enemies.\n9780006482079 Tricked once more by his wily half-brother\\, Lysaer\\, Lord of Light\\, arrives at the tiny harbor town of Merior to find that Arithon\'s ship yards have been abandoned and meticulously destroyed\\, and that the Master of Shadow has disappeared as if into thin air. Meanwhile Arithon and the Mad Prophet Dakar are traveling on foot through the treacherous Kelhorn Mountains towards the Vastmark clans\\, there to raise further support for his cause. But raising a warhost is a costly business. Is it mere coincidence that Princess Talith—Lysaer\'s beautiful\\, headstrong wife—is taken captive and held for a vast ransom by a master brigand? The forces of light and shadow circle and feint\\, drawing ever closer to a huge conflict. And in the background the Fellowship of Seven Sorcerers and the Koriani Enchantresses watch and plan\\, and wait.\n9780006483014 An omnibus volume of the author\'s complete story of the Arthurian epic which includes: \\"The sword in the stone\\" (1939)\\, \\"The witch in the wood\\" (1939)\\, \\"The ill-made knight\\" (1940)\\, \\"The candle in the wind\\" (published for the first time)\\, and \\"The book of Merlyn.\\" 1996.\n9780006483892 Available in the U.S. for the first time\\, this is the second volume in the exceptional Legends of the Riftwar series from \\"New York Times\\"-bestselling authors Feist and Rosenberg.\n9780006483908 Jimmy the Hand\\, boy thief of Krondor\\, lived in the shadows of the city. Though gifted beyond his peers\\, Jimmy is merely a pickpocket with potential--until he aids Prince Arutha in the rescue of Princess Anita from Duke Guy du Bas-Tyra\\, and runs afoul of \\"Black Guy\'s\\" secret police. Facing a choice between disappearing on his own or in a weighted barrel at the bottom of Krondor\'s harbor\\, Jimmy chooses the former. Forced to flee the only home he\'s ever known\\, Jimmy finds himself among the unsuspecting rural villagers of Land\'s End\\, where he hopes to prosper with his talents for con and thievery. But Land\'s End is home to many who tread the crooked path--and to a dark\\, dangerous presence even the local smugglers don\'t recognize. And suddenly Jimmy\'s youthful bravado and courage are leading him into the maw of chaos . . . and\\, quite possibly\\, to his doom.\n9780006486145 Gareth is just a frightened young lad when he is drafted in to be the whipping-boy for the unruly Prince Dagnarus. Yet as they grow to be men\\, an unshakable bond is formed. And it is their destiny for them to become the two most powerful - and feared - men in the kingdom. But when Dagnarus decides to become a knight himself\\, he begins a chain of evil events that threaten to destroy the entire kingdom. Only by uniting the Sovereign Stone can peace be restored\\, and it is up to Dagnarus\' brother Helmos to try to achieve this impossible task\\, using his father\'s soldiers against his brother\'s army. All the while\\, Gareth is gaining mastery over the sinister Void magic\\, and he is devoted to helping his childhood companion.. This gripping story of magical power and corruption takes the unique viewpoint of focusing on the evil characters\\, as we follow them from boys to men. Filled with action\\, suspense and wonderfully imaginative characters\\, Water From the Well of Darkness is set to elevate the careers of bestselling authors Weis & Hickman to spectacular new heights.\n9780006490456 Newly-Jacketed Edition Designed To Celebrate The 50Th Anniversary Of Christie S Faultlessly Plotted Witness For The Prosecution And Other Outstanding Plays. The Perfect Complement To The Latest Edition Of The Mousetrap And Selected Plays (50Th Aniversary Edition). Headlining This Book Is Witness For The Prosecution Christie S Highly Successful Stage Play Which Won The New York Drama Critics Circle Award For Best Foreign Play. A Stunning Courtroom Drama\\, It Tells The Story Of A Scheming Wife Testifying Against Her Husband In A Shocking Murder Trial. The Wild Beauty Of A Seaside House Perched High On The Devonshire River Tern Provides A Stunning Back-Drop In Towards Zero As A Psychopathic Murderer Homes In On The Unsuspecting Victims. Passion\\, Murder And Love Are The Deadly Ingredients In Verdict\\, Making It One Of Christie S More Unusual Thrillers And Prompting Her To Label It The Best Play I Have Written With The Exception Of Witness For The Prosecution . Go Back For Murder Tells The Story Of The Young And Feisty Carla Who\\, Orphaned At The Tender Age Of Five\\, Discovers Her Mother Was Imprisioned For Murdering Her Father And Determines To Prove Her Innocence.')

In [10]:
db_books = Chroma.from_documents(
    documents,
    embedding = OpenAIEmbeddings()
)

In [11]:
query = "A book to teach childrean about nature"

docs = db_books.similarity_search(query,k = 10)
docs

[Document(id='61814b09-e7c5-4bcc-a5de-b271c7e6f1b5', metadata={'source': 'data/tagged_description.txt'}, page_content='9780060852559 Bestselling author Barbara Kingsolver returns with her first nonfiction narrative that will open your eyes in a hundred new ways to an old truth: You are what you eat. \\"As the U.S. population made an unprecedented mad dash for the Sun Belt\\, one carload of us paddled against the tide\\, heading for the Promised Land where water falls from the sky and green stuff grows all around. We were about to begin the adventure of realigning our lives with our food chain. \\"Naturally\\, our first stop was to buy junk food and fossil fuel. . . .\\" Hang on for the ride: With characteristic poetry and pluck\\, Barbara Kingsolver and her family sweep readers along on their journey away from the industrial-food pipeline to a rural life in which they vow to buy only food raised in their own neighborhood\\, grow it themselves\\, or learn to live without it. Their good-humored search yields surprising discoveries about turkey sex life and overly zealous zucchini plants\\, en route to a food culture that\'s better for the neighborhood and also better on the table. Part memoir\\, part journalistic investigation\\, Animal\\, Vegetable\\, Miracle makes a passionate case for putting the kitchen back at the center of family life and diversified farms at the center of the American diet. \\"This is the story of a year in which we made every attempt to feed ourselves animals and vegetables whose provenance we really knew . . . and of how our family was changed by our first year of deliberately eating food produced from the same place where we worked\\, went to school\\, loved our neighbors\\, drank the water\\, and breathed the air.\\"\n9780060853983 According to The Nice and Accurate Prophecies of Agnes Nutter\\, Witch (the world\'s only completely accurate book of prophecies\\, written in 1655\\, before she exploded)\\, the world will end on a Saturday. Next Saturday\\, in fact. Just before dinner. So the armies of Good and Evil are amassing\\, Atlantis is rising\\, frogs are falling\\, tempers are flaring. Everything appears to be going according to Divine Plan. Except a somewhat fussy angel and a fast-living demon—both of whom have lived amongst Earth\'s mortals since The Beginning and have grown rather fond of the lifestyle—are not actually looking forward to the coming Rapture. And someone seems to have misplaced the Antichrist . . .\n9780060854096 She thought her date was out of this world. Actually\\, he was not of this world . . . We\'ve all been on bad dates\\, nightmare dates\\, dreadful experiences that turned out to be uniquely memorable in the very worst way. But at least our partners for these detestable evenings were more or less . . . human! Now Kim Harrison\\, Lynsay Sands\\, Kelley Armstrong\\, and Lori Handeland -- four of the very best writers currently exploring the dangerous seduction of the supernatural -- offer up dating disasters (and unexpected delights) of a completely different sort: dark\\, wicked\\, paranormally sensual assignations with werewolves\\, demon lovers\\, and the romantically challenged undead. Sexy\\, witty\\, chilling\\, and altogether remarkable\\, here is proof positive that some love matches are made someplace other than heaven.\n9780060854942 A powerful literary classic from one of contemporary fiction\'s most acclaimed and important writers\\, Russell Banks\'s Continental Drift is a masterful novel of hope lost and gained\\, and a gripping\\, indelible story of fragile lives uprooted and transformed by injustice\\, disappointment\\, and the seductions and realities of the American dream.\n9780060872793 Bookseller Bernie Rhodenbarr\'s in love—with an exotic Eastern European beauty who shares his obsession with Humphrey Bogart movies. He\'s in heaven\\, munching popcorn with his new amour every night at a Bogart Film Festival—until their Casablanca-esque idyll is cut short by his other secret passion: burglary. When he\'s hired to pilfer a portfolio of valuable documents from a Park Avenue apartment\\, Bernie can hardly refuse. But the occupant\'s early return forces Bernie to flee empty-handed—and he soon finds himself implicated in a murder. Before you can say \\"who stole the strawberries?\\" he\'s hunting for a killer\\, up to his neck in the outrageous intrigues of a tiny Balkan nation . . . and menaced by more sinister fat men and unsavory toadies than the great Bogie himself butted heads with in pursuit of that darn bird!\n9780060872984 Is a loved one missing some body parts? Are blondes becoming extinct? Is everyone at your dinner table of the same species? Humans and chimpanzees differ in only 400 genes; is that why a chimp fetus resembles a human being? And should that worry us? There\'s a new genetic cure for drug addiction—is it worse than the disease? We live in a time of momentous scientific leaps\\, a time when it\'s possible to sell our eggs and sperm online for thousands of dollars and to test our spouses for genetic maladies. We live in a time when one fifth of all our genes are owned by someone else\\, and an unsuspecting person and his family can be pursued cross-country because they happen to have certain valuable genes within their chromosomes . . . Devilishly clever\\, Next blends fact and fiction into a breathless tale of a new world where nothing is what it seems and a set of new possibilities can open at every turn. Next challenges our sense of reality and notions of morality. Balancing the comic and the bizarre with the genuinely frightening and disturbing\\, Next shatters our assumptions and reveals shocking new choices where we least expect. The future is closer than you think.\n9780060880125 Sixteen-year-old Steph Landry finds an old book on how to be popular and decides to change her social status by following its advice\\, much to the bafflement of her two best friends.\n9780060882600 Charlotte\'s Web\\, one of America\'s best-loved children\'s books\\, is seamless in plot\\, poignant in its delineation of characters who will live in children\'s literature forever\\, and written with a seeming ease and fluency that make the reading as engrossing as it is effortless. The Annotated Charlotte\'s Web opens the door to the creator\'s workshop and allows the reader to glance over the shoulder of one of the most exacting and fastidious American writers\\, watching as he forms his masterpiece.\n9780060882860 One of Gabriel García Márquez\'s most intricate and ambitious works\\, The Autumn of the Patriarch is a brilliant tale of a Caribbean tyrant and the corruption of power. From charity to deceit\\, benevolence to violence\\, fear of God to extreme cruelty\\, the dictator of The Autumn of the Patriarch embodies the best and the worst of human nature. Gabriel García Márquez\\, the renowned master of magical realism\\, vividly portrays the dying tyrant caught in the prison of his own dictator-ship. Employing an innovative\\, dreamlike style\\, and overflowing with symbolic descriptions\\, the novel transports the reader to a world that is at once fanciful and real.\n9780060884055 Claudia Corvette. From her tousled bedroom hair to her name–all the porn stars in this world take their names from supermodels and sports cars–she is adult entertainment\'s prototypical femme fatale. Her life is the collision of countless troubled–childhood cliches and grown–up wet dreams\\, projected onto her as surely as her videos project their blue light onto lonely men around the world. From its first panel\\, How to Make Money Like a Porn Star draws the reader into the dark world of girls like Claudia\\, the men who fantasize about them\\, and the monsters who control them. In the hands of Rolling Stone writer Neil Strauss and illustrator Bernard Chang\\, this adult graphic novel weaves together black humor and blacker reality. Like all great American stories\\, it features humble beginnings\\, life–changing tragedy\\, stripping\\, abuse\\, implants\\, fame\\, addiction\\, bigger implants\\, abduction\\, gunplay\\, downfall\\, and even bigger implants. Not to mention a thousand shades of latex and L\'Oreal. Part parody\\, part morality tale\\, here is the truth about the porn life\\, its outsized visual splendor captured in a comic parade of doe–eyed centerfolds\\, its essence distilled in a story that will haunt every reader who has ever wondered where his next fantasy is coming from.\n9780060885373 A year in the life of two young girls growing up on the Wisconsin frontier\\, as they help their mother with the daily chores\\, enjoy their father\'s stories and singing\\, and share special occasions when they get together with relatives or neighbors.\n9780060885380 At the end of the nineteenth century\\, nine-year-old Almanzo lives with his family on a big farm in New York State where he raises his own two calves\\, helps cut ice and shear sheep\\, and longs for the day he can have his own colt.\n9780060885427 After an October blizzard\\, Laura\'s family moves from the claim shanty into town for the winter\\, a winter that an Indian has predicted will be seven months of bad weather. A Newbery Honor Book. Reissue.\n9780060885458 During their first four years of marriage\\, Laura and Almanzo Wilder have a child and fight a losing battle in their attempts to succeed at farming on the South Dakota prairie. Reissue.'),
 Document(id='33f13f10-5f10-4019-af3e-60c2e4f970c2', metadata={'source': 'data/tagged_description.txt'}, page_content='9780064403870 When Margaret and her younger brother\\, Artie\\, get lost in the woods on a family camping trip\\, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat\'s community\\, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do\\, they must protect the rats who have helped them. Everything depends on their silence... but it\'s hard to evade questions forever. Children\'s Choices for 1991 (IRA/CBC)VOYA\'s Best Science Fiction\\, Fantasy\\, and Horror 1990Parenting Honorable Mention\\, Reading Magic Award\n9780064404419 \\"Culled from 69 stories collected in a [1930s] WPA project\\, [these 20] tales are organized into sections with themes like \'Tricksters\' or \'Virtues and Vices\\,\' each with a thoughtful introduction placing the individual stories in the context of feelings and background of the original tellers. Yep\'s telling is vigorous\\, often poetic\\, imbued with earthy humor and realism touched with fatalism. A handsomely designed collection.\\" —K. Notable Children\'s Books of 1989 (ALA) The USA Through Children\'s Books 1990 (ALA) 1989 Boston Globe–Horn Book Award for Nonfiction 1990 Fanfare Honor List (The Horn Book) 1989 Children\'s Editors\' Choices (BL) Notable 1989 Children\'s Trade Books in Social Studies (NCSS/CBC) Children\'s Books of 1989 (Library of Congress) 1989 Children\'s Books (NY Public Library) \\"The Best Books\\" 1989 (Parents Magazine)\n9780064404891 In 1867\\, Otter travels from Three Willows Village in China to California -- the Land of the Golden Mountain. There he will join his father and uncle. In spite of the presence of family\\, Otter is a stranger among the other Chinese in this new land. And where he expected to see a land of goldfields\\, he sees only vast\\, cold whiteness. But Otter\'s dream is to learn all he can\\, take the technology back to the Middle Kingdom\\, and free China from the Manchu invaders. Otter and the others board a machine that will change his life -- a train for which he would open the Dragon\'s Gate.\n9780064405447 Betsy marries Joe\\, her high school sweetheart\\, and they have all the problems of young newlyweds\\, in a sixtieth anniversary edition of a beloved story which includes a new biographical section and a new forward. Original.\n9780064405454 In January 1914\\, with an unsuccessful college experience and a broken romance with Joe behind her\\, twenty-one-year-old Betsy\\, traveling alone for the first time\\, determines to enjoy every moment of her long trip around Europe.\n9780064405478 A small town shortly after the turn of the century provides the background for this account of Betsy\'s third year at Deep Valley High. Reissue.\n9780064405713 Increasingly alienated from his widowed father\\, Vernon joins his friends in ridiculing the neighborhood outcasts\'Maxine\\, an alcoholic prone to outrageous behavior\\, and Ronald\\, her retarded son. But when a social service agency tries to put Ronald into a special home\\, Vernon fights against the move. 1994 Newbery Honor Book Notable Children\'s Books of 1994 (ALA) 1994 Best Books for Young Adults (ALA) 1994 Young Adult Editors\' Choices (BL) 1994 Books for the Teen Age (NY Public Library) Young Adult Choices for 1995 (IRA)\n9780064405850 The land was theirs\\, but so were its hardships Strawberries -- big\\, ripe\\, and juicy. Ten-year-old Birdie Boyer can hardly wait to start picking them. But her family has just moved to the Florida backwoods\\, and they haven′t even begun their planting. \\";Don′t count your biddies ′fore they′re hatched\\, gal young un!\\"; her father tells her. Making the new farm prosper is not easy. There is heat to suffer through\\, and droughts\\, and cold snaps. And\\, perhaps most worrisome of all for the Boyers\\, there are rowdy neighbors\\, just itching to start a feud.\n9780064405959 When seven Siberian snow spiders\\, frozen during the Ice Age\\, defrost and escape en route to Harvard for analysis\\, they wreak havoc on a small New England town\\, disrupting the school Halloween pageant with hilarious results. An ALA Notable Children\'s Book. Reissue.\n9780064406307 \'Like Cushman\'s 1995 Newbery Honor Book\\, Catherine\\, Called Birdy\\, this novel is about a strong young woman in medieval England who finds her own way home. This is a world\\, like Chaucer\'s\\, that\'s . . . dangerous\\, primitive and raucous. From the first page you\'re caught by the spirit of the homeless\\, nameless waif\\, somewhere around 12 years old. She gets the village midwife to take her in\\, befriends a cat\\, names herself Alyce\\, and learns something about delivering babies. When she fails\\, she runs away\\, but she picks herself up again and returns to work and independence.\' --ALA Booklist (starred review). \'. . .A fascinating view of a far distant time.\' -- The Horn Book (starred review)\n9780064406925 The Little House books tell the story of a little pioneer girl and her family as they traveled by covered wagon across the Midwest. Laura Ingalls Wilder\'s classic books\\, illustrated with Garth Williams\' timeless artwork\\, have been cherished by millions of readers ever since they were first published over sixty years ago. This My First Little House Book introduces Almanzo Wilder\\, the young boy from Farmer Boy who would one day marry Laura Ingalls. In Winter on the Farm\\, Almanzo goes through his afternoon barn chores\\, and then sits down to eat a hearty farm supper with his family. In this first book about Almanzo\\, young readers are able to share in the warmth and joy of another Little House family and celebrate new Little House adventures. Winter on the Farm is the first in an ongoing series about Laura’s beloved farmer boy.\n9780064407144 With the arrival of her new governess\\, Miss Crow\\, Martha begins to see that her work is quite important and soon realizes she could learn a great deal from her if she only took the time to get to know her. Simultaneous.\n9780064407311 FADE IN: INTERIOR: Early morning in CELL BLOCK D\\, MANHATTAN DETENTION CENTER. Steve (Voice-Over) Sometimes I feel like I have walked into the middle of a movie. Maybe I can make my own movie. The film will be the story of my life. No\\, not my life\\, but of this experience. I\'ll call it what the lady prosecutor called me ... Monster.\n9780064408585 After graduating high school\\, Emily Webster longs to go off to university with everyone else\\, but she must stay at home and take care of her grandfather\\, a Civil War veteran\\, and it is at home that she discovers many new adventures. Reprint.\n9780064408677 Swan Song Like the rest of his family\\, Louis is a trumpeter swan. But unlike his four brothers and sisters\\, Louis can\'t trumpet joyfully. In fact\\, he can\'t even make a sound. And since he can\'t trumpet his love\\, the beautiful swan Serena pays absolutely no attention to him. Louis tries everything he can think of to win Serena\'s affection -- he even goes to school to learn to read and write. But nothing seems to work. Then his father steals him a real brass trumpet. Is a musical instrument the key to winning Louis his love?\n9780064408745 Now an old man living in the United States\\, Marcel recalls his childhood in German-occupied France\\, especially the summer that he and his older brother RenT befriended a young German soldier. Reprint.\n9780064409902 After grasshoppers ruin the crops\\, eight-year-old Laura Ingalls and her family leave Plum Creek and move to Burr Oak\\, Iowa\\, where they experience life in a small town and help manage a hotel. Reprint.\n9780064410342 In the land of Ingary\\, such things as spells\\, invisible cloaks\\, and seven-league boots were everyday things. The Witch of the Waste was another matter. After fifty years of quiet\\, it was rumored that the Witch was about to terrorize the country again. So when a moving black castle\\, blowing dark smoke from its four thin turrets\\, appeared on the horizon\\, everyone thought it was the Witch. The castle\\, however\\, belonged to Wizard Howl\\, who\\, it was said\\, liked to suck the souls of young girls. The Hatter sisters--Sophie\\, Lettie\\, and Martha--and all the other girls were warned not to venture into the streets alone. But that was only the beginning. In this giant jigsaw puzzle of a fantasy\\, people and things are never quite what they seem. Destinies are intertwined\\, identities exchanged\\, lovers confused. The Witch has placed a spell on Howl. Does the clue to breaking it lie in a famous poem? And what will happen to Sophie Hatter when she enters Howl\'s castle? Diana Wynne Jones\'s entrancing fantasy is filled with surprises at every turn\\, but when the final stormy duel between the Witch and the Wizard is finished\\, all the pieces fall magically into place.\n9780064410724 The students\' scheme to find a love match for their beloved teacher on Valentine\'s Day turns into a comedy of errors when four stupid cupids from Ancient Greece try to help.\n9780064410939 Beloved by generations\\, Charlotte\'s Web and Stuart Little are two of the most cherished stories of all time. Now\\, for the first time ever\\, these treasured classics are available in lavish new collectors\' editions. In addition to a larger trim size\\, the original black-and-white art by Garth Williams has been lovingly colorized by renowned illustrator Rosemary Wells\\, adding another dimension to these two perfect books for young and old alike.'),

In [12]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
260,9780060852559,0060852550,"Animal, Vegetable, Miracle",Barbara Kingsolver;Camille Kingsolver;Steven L...,Biography & Autobiography,http://books.google.com/books/content?id=qLkEY...,Bestselling author Barbara Kingsolver returns ...,2007.0,4.04,370.0,86130.0,"Animal, Vegetable, Miracle: A Year of Food Life",9780060852559 Bestselling author Barbara Kings...

In [13]:
def retrieve_semantic_recommendations(query: str, top_k: int = 10):
    recs = db_books.similarity_search(query, k=50)

    books_list = []
    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)].head(top_k)

In [15]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
86,9780060000141,0060000147,Poppy's Return,Avi,Juvenile Fiction,http://books.google.com/books/content?id=XbcMJ...,"There's trouble at Gray House, the girlhood ho...",2006.0,3.99,256.0,1086.0,Poppy's Return,"9780060000141 There's trouble at Gray House, t..."
101,9780060175641,0060175648,Identity,Milan Kundera,Fiction,http://books.google.com/books/content?id=D30Ex...,Milan Kundera's Identity translated from the F...,1998.0,3.68,176.0,260.0,Identity: A Novel,9780060175641 Milan Kundera's Identity transla...
114,9780060509057,0060509058,Travels,Michael Crichton,Biography & Autobiography,http://books.google.com/books/content?id=QYilZ...,Often I feel I go to some distant region of th...,2002.0,3.95,400.0,6812.0,Travels,9780060509057 Often I feel I go to some distan...
203,9780060736255,0060736259,Weetzie Bat,Francesca Lia Block,Juvenile Fiction,http://books.google.com/books/content?id=vxCXx...,Fifteen years ago Francesca Lia Block made a d...,2004.0,3.74,128.0,12771.0,Weetzie Bat,9780060736255 Fifteen years ago Francesca Lia ...
218,9780060763725,0060763728,Psyche in a Dress,Francesca Lia Block,Juvenile Fiction,http://books.google.com/books/content?id=NYE3G...,But this is what I could not give up: I could ...,2006.0,3.84,116.0,2414.0,Psyche in a Dress,9780060763725 But this is what I could not giv...
260,9780060852559,0060852550,"Animal, Vegetable, Miracle",Barbara Kingsolver;Camille Kingsolver;Steven L...,Biography & Autobiography,http://books.google.com/books/content?id=qLkEY...,Bestselling author Barbara Kingsolver returns ...,2007.0,4.04,370.0,86130.0,"Animal, Vegetable, Miracle: A Year of Food Life",9780060852559 Bestselling author Barbara Kings...
306,9780060932664,006093266X,Collected Novellas,Gabriel Garcia Marquez,Fiction,http://books.google.com/books/content?id=JRcVu...,"Renowned as a master of magical realism, Gabri...",1999.0,4.01,288.0,822.0,Collected Novellas,9780060932664 Renowned as a master of magical ...
363,9780061120077,0061120073,A Tree Grows in Brooklyn,Betty Smith,Fiction,http://books.google.com/books/content?id=Y-FZ9...,The beloved American classic about a young gir...,2006.0,4.26,496.0,326733.0,A Tree Grows in Brooklyn,9780061120077 The beloved American classic abo...
388,9780061196676,0061196673,Smithsonian Intimate Guide to Human Origins,Carl Zimmer,Social Science,http://books.google.com/books/content?id=xufuS...,From the savannas of Africa to modern-day labs...,2007.0,4.00,176.0,167.0,Smithsonian Intimate Guide to Human Origins,9780061196676 From the savannas of Africa to m...
406,9780064403870,0064403874,"R-T, Margaret, and the Rats of NIMH",Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=WTHHH...,"When Margaret and her younger brother, Artie, ...",1991.0,3.52,272.0,631.0,"R-T, Margaret, and the Rats of NIMH",9780064403870 When Margaret and her younger br...